### ISSUE TITLE
Up it to 4.03.0

### ISSUE THREAD

**Issue by fxfactorial** [ocaml-cross/opam-cross-ios#1]
Could you up to this 4.03.0?

**Comment by whitequark** [comment]
The 4.03 port is not available upstream yet: http://psellos.com/ocaml/compile-to-iphone.html.

**Comment by fxfactorial** [comment]
Ah, I didn't realize you were using Jeff's stuff as well.

**Comment by jordwalke** [comment]
I would definitely love to see this happen as well (or perhaps targeting 4.04). This seems like the best place to voice that (as there doesn't seem to be any other project on GitHub)

**Comment by whitequark** [comment]
@jordwalke In general, outside of merging new OPAM files and fixing packaging bugs, I only provide commercial support for the `opam-cross-*` compilers and packages. You can contact me at whitequark@whitequark.org if that's something you are interested in.

**Comment by jordwalke** [comment]
Thanks so much for the work you've done so far, and I'll definitely contact you at some point.

**Comment by whitequark** [comment]
It's at 4.04.0 already (and for a good while).

**Comment by jordwalke** [comment]
Thank you, @whitequark !

**Comment by jordwalke** [comment]
Curious, wasn't there an iOS patch for 4.02.3 that never made it upstream? How did you accomplish 4.04 support?

**Comment by whitequark** [comment]
I rebased the patch on top of 4.04.0.

**Comment by jordwalke** [comment]
Wow, that's great to hear that it didn't have any conflicts (I suppose ARM support has been relatively stable). Do you recall if there was any hesitation to accept the patch upstream? I ask because multicore support will need to touch ARM generation, and since they haven't began yet it might be better to do it before they start, lest there be conflicts.

**Comment by whitequark** [comment]
> Wow, that's great to hear that it didn't have any conflicts

Of course it did. I spent several days working on that.

**Comment by jordwalke** [comment]
Congrats, and thanks! Any plans up sending a PR upstream?

@let-def may be willing to help manage that if you need any help (Sorry to volunteer you Fred, but we've discussed this in the past, and you seemed interested at the time).

**Comment by whitequark** [comment]
https://github.com/ocaml/ocaml/pull/1084

**Comment by let-def** [comment]
@jordwalke I can help with reviewing, but I won't have access to a macOS machine in the next two weeks.

**Comment by whitequark** [comment]
You can use a VM, like I do. (I don't own any Apple hardware.)

**Comment by let-def** [comment]
Clever. Any setup to suggest? Standard installer with qemu/kvm will do?

**Comment by whitequark** [comment]
www.contrib.andrew.cmu.edu/~somlo/OSXKVM/. For Sierra (I think Yosemite+, actually) you'll need to install Clover in UEFI mode first; Enoch or Chameleon won't do. I have this script I use to start it:

```
#!/bin/sh -ex

qemu-system-x86_64 \
  -enable-kvm \
  -machine pc-q35-2.4 \
  -cpu Penryn,vendor=GenuineIntel \
  -smp 4,cores=2 \
  -m 4096 \
  -bios /usr/share/qemu/OVMF.fd \
  -usb -device usb-kbd -device usb-tablet \
  -device VGA,vgamem_mb=64 \
  -device isa-applesmc,osk="[REDACTED]" \
  -device ide-drive,bus=ide.0,drive=hdd3 \
  -drive id=hdd3,if=none,file=clover.img \
  -device ide-drive,bus=ide.1,drive=hdd2 \
  -drive id=hdd2,if=none,file=osx.img \
  -device ide-drive,bus=ide.2,drive=hdd1 \
  -drive id=hdd1,if=none,file=/dev/raidho/vm-macos-sierra,format=raw \
  -netdev user,id=net0,hostfwd=tcp::2222-:22,tcp::2223-:22 \
  -device e1000-82545em,netdev=net0,id=net0,mac=52:54:00:c9:18:2a \
  -device intel-hda \
  -device hda-duplex \
  $*
```

**Comment by whitequark** [comment]
Note the usb-tablet doesn't work with the installer, you need this driver: http://philjordan.eu/osx-virt/

**Comment by let-def** [comment]
@whitequark Thanks!

**Comment by jordwalke** [comment]
Looks pretty complicated. If it's too much trouble, @let-def, I will just loan you a mac 😆 

Though it would be really nice to be able to build for every major OS from one OS that is not OS X.

**Comment by whitequark** [comment]
You can do that with Travis and Appveyor, I think, which is even legal.
