### ISSUE TITLE
question about cross for Mac OS from Linux.

### ISSUE THREAD

**Issue by sandreenko** [ocaml-cross/opam-cross-ios#13]
Hello, I am not sure if this is the right repo, but is there a plan to support cross-compilation from x64 Linux to x64/arm64 Mac? If there are big obstacles for that is there any description of them to estimate the cost of such support?

What about the reverted scenario of host mac and target linux?

Thank you.

**Comment by dboris** [comment]
I have set up a macOS cross toolchain [here](https://github.com/dboris/opam-cross-macos). The reverted scenario should also be possible if someone has interest to do it.

**Comment by dboris** [comment]
See also [OCamlPro/opam-cross-osx](https://github.com/OCamlPro/opam-cross-osx)
