### ISSUE TITLE
ocamlfind: Package `threads' not found

### ISSUE THREAD

**Issue by nickmain** [ocaml-cross/opam-cross-ios#18]
macOS Sonoma, M1 Mac Mini.

After following the README instructions for setting up a 5.0.0 switch for the simulator (ARCH=arm64 SUBARCH=arm64) attempting to build the sample program results in an ocamlfind error:

```
ocamlfind -toolchain ios ocamlopt -package re.pcre -linkpkg -output-complete-obj test_pcre.ml -o test_pcre.o
ocamlfind: Package `threads' not found
```

Querying threads does work:
```
ocamlfind query threads
/Users/nickmain/.opam/ios-sim/lib/ocaml/threads
```

**Comment by dboris** [comment]
I reproduced the issue and will look for a solution. In the meantime, I suggest you try the `4.14.2` compiler which should work fine.

**Comment by dboris** [comment]
Pushed a fix. Let me know if it works for you.

**Comment by nickmain** [comment]
The fix worked - I can build.
Thank you!
