### ISSUE TITLE
Cannot get C runtime compiled

### ISSUE THREAD

**Issue by saschatimme** [ocaml-cross/opam-cross-ios#8]
I try to get a simple example from http://www.mega-nerd.com/erikd/Blog/CodeHacking/Ocaml/index.html running on iOS but end up with the following error:
<img width="1680" alt="screen shot 2017-07-20 at 10 33 29" src="https://user-images.githubusercontent.com/4854317/28408277-39ffaba6-6d37-11e7-86c8-629ebbe5c529.png">

To my XCode configuration:
I added `/Users/sascha/.opam/4.04.0+ios+amd64/ios-sysroot/lib/ocaml/` to my library and header search paths and added `libasmrun.a` from `/Users/sascha/.opam/4.04.0+ios+amd64/ios-sysroot/lib/ocaml/` as a library to XCode.

To install everything I followed your readme instructions,

Any assistance would be greatly appreciated!

**Comment by whitequark** [comment]
Use `-output-complete-obj` ocamlopt flag instead of `-output-obj` and adding `libasmrun.a` manually.

**Comment by saschatimme** [comment]
Got it running! Thank you for your help and your work on this stuff :)
